branch-defaults:
  master:
    environment: eb-biosys-uat
  prod:
    environment: eb-biosys-prod
  staging:
    environment: eb-biosys-staging
  uat:
    environment: eb-biosys-uat
global:
  application_name: eb-biosys
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
