branch-defaults:
  aws_ebeanstalk:
    environment: eb-biosys-uat
    group_suffix: null
  master:
    environment: eb-biosys-uat
global:
  application_name: eb-biosys
  branch: uat
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
